source_language = "en"
target_language = "de"

source_files = "en_(\\d+).md"
target_files = "de_\\1.md"

terms = '''
Economics: Wirtschaftslehre
Economist: Ökonom
Economy: Wirtschaft
economical: wirtschaftlich
Exchange/Trade: Handel
'''

